### ISSUE TITLE
Add postinstall script

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-common-tools#1]
So I don't have to do the links myself...

**Comment by BarryThePenguin** [comment]
This looks promising [broccolijs/node-symlink-or-copy](https://github.com/broccolijs/node-symlink-or-copy)

Would be useful for windows environments

**Comment by kentcdodds** [comment]
Oh cool. Thanks for the tip!

**Comment by kentcdodds** [comment]
This repo needs some serious love. I should just make it a true CLI so users don't have to install dependencies themselves.
